### PR TITLE
chore: update for new renku image

### PR DESCRIPTION
**Pull request by rokroskar**

### CODE REVIEW

**Comment by emmjab** [comment]
@cchoirat suggested updating the names from "python minimal" and "R minimal" to indicate which versions of python and R we're providing (i.e. "Python 3.7 minimal", "R 3_10 minimal"), and include the other images we have in this list (R bioconductor, etc)

**Comment by rokroskar** [comment]
To include other images we should make more template projects. 

Regarding the versions - I personally think it would make the drop-down cluttered especially if we don't offer any alternatives (i.e. we only offer a single version of R and python). What if we put that information in the template description?

**Comment by emmjab** [comment]
I thought the goal was to offer more from the dropdown (i.e. the other dockerfile bases, like bioconductor, etc; and offer the cuda one on gpu-available instances)

**Comment by rokroskar** [comment]
Sure but that's not in the scope of this PR. It depends on https://github.com/swissdatasciencecenter/renku-python/issues/862 and related issues to be implemented.

**Comment by rokroskar** [comment]
Thanks for the review @emmjab! I have discussed the issue I linked above with @lorenzo-cavazzi and we will try to prioritize it this sprint so that we can move forward with the templating.

**Pull request merged**
