### PR TITLE
build: add .Rproj file

### PR DESCRIPTION
**Pull request by emmjab**
templated file name for R projects

when this is merged, can take out same content from `entrypoint.sh` in renkulab-docker's `docker/r/entrypoint.sh`.

### CODE REVIEW

**Review by rokroskar — CHANGES_REQUESTED** [review]
Using a project name with spaces results in a filename with spaces - they should be replaced with dashes since that is what is used in the project slug.

**Comment by rokroskar** [comment]
@Panaetius you think the name fix should be done in core or here?

**Comment by rokroskar** [comment]
I made the change to use the newly-added `__sanitized_project_name__` variable in the template to create the RProj file and it seems to work.

**Review by ableuler — APPROVED** [review]
I didn't test this in my own environment but the project in the link looks good and the changes make sense.

**Review by rokroskar — APPROVED** [review]

**Pull request merged**
