### PR TITLE
New templates

### PR DESCRIPTION
**Pull request by rokroskar**
closes https://github.com/SwissDataScienceCenter/renku-project-template/issues/27

### CODE REVIEW

**Comment by rokroskar** [comment]
How about:

```yaml
templates:
  python-minimal:
    folder: python-minimal
    name: Basic Python Project
    description: The simplest renku project with a basic directory structure and necessary supporting files.
```

**Comment by ciyer** [comment]
I considered something like this, but it makes it more difficult for the creator of templates to control the order in which they appear. For me, that was an argument against this, but maybe it doesn't matter.

**Comment by rokroskar** [comment]
Agreed, should be a list

**Comment by rokroskar** [comment]
The other thing to consider here is whether we want to make these cookie-cutter compatible?

**Pull request merged**
