### PR TITLE
refactor: remove renku metadata files

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
We don't need any `.renku/metadata.yml` file anymore since it will be added by `renku init` once SwissDataScienceCenter/renku-python#809 will be merged.

Please don't merge this PR for now. The ui still needs the file and in the meanwhile the command line will overwrite the file.

### CODE REVIEW

**Comment by lorenzo-cavazzi** [comment]
@rokroskar this could be merged now, right? It's been a while, so I am not confident there isn't a reason I am not aware of to not merge this yet :grin:

**Comment by rokroskar** [comment]
This is waiting for your backend endpoint ;)

**Comment by lorenzo-cavazzi** [comment]
ouch right, for the UI we still need that

**Comment by rokroskar** [comment]
I believe it's time to do this now @lorenzo-cavazzi 😄

**Comment by lorenzo-cavazzi** [comment]
The time has come!
If you want to test, it's possible to create projects from this commit here https://lorenzotest.dev.renku.ch

**Review by rokroskar — APPROVED** [review]

**Pull request merged**
