### PR TITLE
use template variables for language versions

### PR DESCRIPTION
**Pull request by rokroskar**
This implements using template variables for selecting a language version. 

To test on dev, use [this link](https://dev.renku.ch/projects/new?data=eyJ0aXRsZSI6InRlbXBsYXRlLXZlcnNpb25zLXRlc3QiLCJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vU3dpc3NEYXRhU2NpZW5jZUNlbnRlci9yZW5rdS1wcm9qZWN0LXRlbXBsYXRlIiwicmVmIjoiMDAwLXRlbXBsYXRlLXZlcnNpb25zIn0%3D).

### CODE REVIEW

**Review by olevski — APPROVED** [review]

**Review by lorenzo-cavazzi — APPROVED** [review]
That works well!
I guess in the UI we can remove the label `Optional` for variables of type `enum` with a default value

**Comment by rokroskar** [comment]
Well, it is technically optional to choose one since we already set the default. So I'm not sure I would even bother at this point.

**Comment by rokroskar** [comment]
Ok I will merge this but not tag a new release. We can let it simmer on dev for a while.

**Comment by rokroskar** [comment]
haha turns out I made an issue for this a long time ago: https://github.com/SwissDataScienceCenter/renku-project-template/issues/35

**Pull request merged**
