### PR TITLE
chore: cleanup unused dirs and add readme

### PR DESCRIPTION
**Pull request by emmjab**
Mostly self-explanatory, but the idea is just to remove the older template format, which consisted of directories versioned by renku release (i.e. 0.3.0, 0.4.0). The current template just requires what's in the `manifest.yml`.

### CODE REVIEW

**Comment by rokroskar** [comment]
@pameladelgado I guess there are no renkus 0.4.0 floating around in the world? If there are, this PR will break them.

**Comment by emmjab** [comment]
will the renku 0.4.0s not be using a tag at an earlier commit when 0.4.0 still exists?

**Comment by rokroskar** [comment]
No - before renku 0.5.0 (I think) this repo was read as is and versions were in sub-directories (not tags).

**Comment by rokroskar** [comment]
One nit about the readme - could you word-wrap to 80-characters (or some other line length)? Having really long single lines is not so nice.

**Comment by emmjab** [comment]
wait @rokroskar - do you mean on the readme itself or in the code? i fixed it in the code.

**Comment by rokroskar** [comment]
I meant exactly what you did :)

**Comment by pameladelgado** [comment]
> @pameladelgado I guess there are no renkus 0.4.0 floating around in the world? If there are, this PR will break them.

I highly doubt there are such deployments :) and if there are they should update asap! 0.4.0 is almost year old already!

**Pull request merged**
